@startuml カレーライスの作り方
title カレーライスの作り方
|ユーザ|
start
:食材を用意する;
:お米を研ぐ;
fork
|ユーザ|
:野菜を洗う;
:具材を切る;
:鍋に油をひく;
:具材を炒める;
note right: 肉、野菜の順に炒める
:具材を煮る;
note right: 水を加え、沸騰したらあくを取る
:ルーを入れて煮込む;
fork again
:お米を炊く;
end fork
:お皿にお米とカレーを盛りつける;
stop
@enduml