@startuml 共同開発
left to right direction
actor 管理者 as admin
actor 利用者 as user
rectangle 出席管理システム {
usecase 管理者ログイン as login1
usecase 利用者アカウント登録 as ur
usecase 利用者アカウント保守 as um
usecase 学科情報登録 as dr
usecase 学科情報保守 as dm
usecase 利用者ログイン as login2
usecase クラス情報登録 as cr
usecase クラス情報保守 as cm
usecase 学生情報登録 as sr
usecase 学生情報保守 as sm
usecase 出席情報登録 as ar
usecase 出席情報保守 as am
}
admin --> login1
admin --> ur
admin --> um
admin --> dr
admin --> dm
admin --> sm
login2 <-- user
cr <-- user
cm <-- user
sr <-- user
sm <-- user
ar <-- user
am <-- user


@enduml