@startuml  
left to right direction
actor 管理者
actor 利用者

rectangle 出席管理システム{
    usecase 管理者ログイン
    usecase 利用者アカウント登録
    usecase 利用者アカウント保守
    usecase 利用者アカウント削除
    usecase 学科情報登録
    usecase 学科情報保守
    usecase 学科情報削除
    usecase 学科情報修正
    usecase 学生情報登録
    usecase 学生情報保守
    usecase 学生情報削除
    usecase 学生情報修正
    usecase 利用者ログイン
    usecase クラス情報登録
    usecase クラス情報保守
    usecase クラス情報削除
    usecase クラス情報修正
    usecase 出席情報登録
    usecase 出席情報保守
    usecase 出席情報修正
}

管理者 -- 管理者ログイン
管理者 - 利用者アカウント登録
管理者 - 利用者アカウント保守
管理者 -- 学科情報登録
管理者 -- 学科情報保守
管理者 -- 学生情報保守
学生情報保守 --- 利用者
学生情報登録 -- 利用者
利用者ログイン -- 利用者
クラス情報登録 -- 利用者
クラス情報保守 - 利用者
出席情報登録 -- 利用者
出席情報保守 - 利用者

利用者アカウント保守 <|-- 利用者アカウント削除
学科情報保守 <|-- 学科情報修正
学科情報保守 <|-- 学科情報削除
学生情報保守 <|-left- 学生情報修正
学生情報保守 <|-right- 学生情報削除
クラス情報削除 --|> クラス情報保守
出席情報修正 --|> 出席情報保守


@enduml