@startuml ホテル宿泊予約
left to right direction
object "<u>利用者1: 利用者</u>" as a {

}
object "<u>利用者2: 利用者</u>" as b {

}

object "<u>ホテル情報1: 301号室</u>" as hotel{
客室 = シングル
宿泊費 = 1日 = 1万1千円
キャンペーン価格 = 9千円
}
object "<u>ホテル情報1: 302号室</u>" as hotel{
客室 = シングル
宿泊費 = 1日 = 1万1千円
キャンペーン価格 = 9千円
}
object "<u>ホテル情報1: 303号室</u>" as hotel{
客室 = シングル
宿泊費 = 1日 = 1万1千円
キャンペーン価格 = 9千円
}
@enduml