@startuml Web画像検索
hide footbox
skinparam style strictuml
actor "<U>:ユーザー</u>" as user
participant ":ブラウザ" as browser
participant ":Webサーバー" as server1
participant "画像サーバー" as server2

activate user
    user -> browser: 画像のリンクボタンを押す()
    activate browser
    browser -> server1: 画像を探す(画像ファイル名)
        activate server1
        server1 -> server2: 画像ファイルを探す(画像ファイル名)
        activate server2
        server1 <-- server2: 閲覧許可(画像ファイル)
        deactivate server2
        browser <-- server1: 画像を再生(画像ファイル)
        deactivate server1
    deactivate browser

@enduml