@startuml ホテル宿泊予約
left to right direction
object "<u>利用者1: 利用者</u>" as customer1 {
名前 = A
住所
電話番号
}
object "<u>利用者2: 利用者</u>" as customer2 {
名前 = B
住所
電話番号
}
object "<u>ホテル: ホテル</u>" as hotel1 {
部屋 = 301号室
}
object "<u>ホテル: ホテル</u>" as hotel2 {
部屋 = 303号室
}
object "<u>301号室: 部屋</u>" as room1 {
タイプ = シングル
価格 = 1泊 = 11,000円
キャンペーン価格 = 9,000円
}
object "<u>303号室: 部屋</u>" as room2 {
タイプ = シングル
価格 = 1泊 = 11,000円
キャンペーン価格 = 9,000円
}
customer1 -- hotel1
hotel1 -- room1
customer2 -- hotel2
hotel2 -- room2
@enduml