@startuml 演習2-6
left to right direction
actor 利用者 #DDDDDD;line:black;line.bold;
actor ホテル従業員 #DDDDDD;line:black;line.bold;
actor ホテル管理者 #DDDDDD;line:black;line.bold;
rectangle ホテル予約システム {
usecase 空室状況を閲覧する
usecase キャンペーン価格
usecase 空室状況を入力する
usecase 予約を集計する
usecase ログインする
usecase 会員登録をする
(<u>部屋を予約する</u>\n拡張点\nキャンペーン期間) as input
}
利用者 --> input
利用者 --> 空室状況を閲覧する
利用者 --> 会員登録をする
input ..> ログインする : <<include>>
input <. (キャンペーン価格) : <<extend>>
input .> 会員登録をする : <<include>>
会員登録をする <.. ログインする : <<include>>
空室状況を入力する <-- ホテル従業員
予約を集計する <-- ホテル管理者
ログインする <.. 空室状況を入力する : <<include>>
ログインする <.. 予約を集計する : <<include>>
ホテル従業員 <|- ホテル管理者
@enduml