@startuml 演習6-3-2
' left to right direction
[*] -right-> メニュー: 接続する
メニュー --> 予約と確認: 予約する
予約と確認 --> メニュー: 予約を登録する
予約と確認 -> あなたの順番: 登録する
予約と確認 -> あなたの順番: 順番を確認する
あなたの順番 -up-> メニュー: 用紙使用
今の順番 -up-> メニュー: 1つ上げる
メニュー -right-> [*]: 終了
@enduml