@startuml データ更新コントローラとホテルと予約
hide footbox
skinparam style strictuml
participant "controller: データ更新コントロール" as controller
participant "hotel: ホテル" as hotel
participant "予約: ホテル" as reserve

activate controller
    controller -> hotel: 予約操作を呼び出す()
    activate hotel
    create reserve
            hotel -> reserve: 作成する() <<create>>
            hotel -> hotel: 予約登録操作を呼び出す()
            activate hotel
        

@enduml